kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
## Build in 20.04/Noetic
- name: build-20-04
  image: amarburg/drone-ci-ros-noetic:latest
  commands:
    - wget -O- https://gitlab.com/amarburg/ros_drone_ci/-/raw/master/bootstrap.sh | /bin/bash
  environment:
    WSTOOL_RECURSIVE: true

