controller_list:
  - name: fake_testbed_controller
    type: $(arg fake_execution_type)
    joints:
      - corexy_x
      - corexy_y
      - z_axis
      - yaw
initial:  # Define initial robot poses per group
  - group: testbed
    pose: start