controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - bravo_axis_g
      - bravo_axis_f
      - bravo_axis_e
      - bravo_axis_d
      - bravo_axis_c
      - bravo_axis_b
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - bravo_axis_a
initial:  # Define initial robot poses per group
  - group: arm
    pose: rest