# @package _global_

defaults:
  - /training: default
  - /model: tsgraspnet
  - /data: acronymvid
  - _self_

## Enjoy setup
checkpoint: tsgraspnet_11_17_kern5/model.ckpt # relative path to .ckpt from ckpts

data:
  data_cfg:
    points_per_frame: 20000
    dataroot: ${hydra:runtime.cwd}/data/acronymvid

training:
  gpus: 1
  batch_size: 1
  animate_outputs: True
  viz:
    save_outputs: True
    output_dir: ${hydra:runtime.cwd}/figs/ctn_11_17
  make_sc_curve: False
  resume_from_checkpoint: ${hydra:runtime.cwd}/ckpts/${checkpoint}