# @package _global_

# defaults:
#   - model: ???
#   - data: acronymvid
#   - training: default   # needed for batch_size, etc.
#   - _self_

# ckpt_path: ???
# output_name: ???
# output_path: ${hydra:runtime.cwd}/experiments/${output_name}

# description: ??? # Informative blurb about the model being saved.

## Test config
defaults:
  # - /model: tsgraspnet
  # - /data: acronymvid
  - /training: default   # needed for batch_size, etc.
  - /data: scene_renderer_dm
  - _self_

data:
  data_cfg:
    # dataroot: /scratch/playert/workdir/tsgrasp/data/acronymvid
    num_workers: 0
    points_per_frame: 45000
    
    frames_per_traj: 1
    min_pitch: 0.0 # 0 degrees (looking straight down)
    max_pitch: 1.222 # 70 degrees


# ckpt_path: ${hydra:runtime.cwd}/ckpts/tsgraspnet_11_17/model.ckpt
output_name: contact_graspnet_outputs
output_path: ${hydra:runtime.cwd}/experiments/${output_name}.h5

description: This is a test run of the output saver for contact_graspnet.

training:
  gpus: 1
  batch_size: 8

CGN_FLAGS:
  ckpt_dir: /home/tim/Research/contact_graspnet/checkpoints/scene_test_2048_bs3_hor_sigma_001
  forward_passes: 1
  arg_configs: []

pt_radius: 0.005