name: tsgrasp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - anaconda::openblas-devel
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.16
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.5.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cudatoolkit=11.1.74
  - ffmpeg=4.3
  - freetype=2.10.4
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - h5py=3.3.0
  - hdf5=1.10.6
  - intel-openmp=2021.3.0
  - jpeg=9b
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnghttp2=1.43.0
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuv=1.42.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2020.2
  - ncurses=6.2
  - nettle=3.6
  - ninja=1.10.2
  - numpy=1.21.2
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1l
  - pillow=8.3.1
  - pip=21.2.4
  - python=3.8.12
  - python_abi=3.8
  - pytorch=1.9.0
  - readline=8.1
  - setuptools=58.0.4
  - sqlite=3.36.0
  - tk=8.6.11
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - trimesh=3.9.30
  - typing_extensions=3.10.0.0
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.13.0
    - aiohttp==3.7.4.post0
    - antlr4-python3-runtime==4.8
    - async-timeout==3.0.1
    - attrs==21.2.0
    - cachetools==4.2.2
    - certifi==2021.5.30
    - chardet==4.0.0
    - charset-normalizer==2.0.6
    - click==8.0.1
    - configparser==5.0.2
    - docker-pycreds==0.4.0
    - fsspec==2021.8.1
    - future==0.18.2
    - gitdb==4.0.7
    - gitpython==3.1.18
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.40.0
    - hydra-core==1.1.1
    - idna==3.2
    - importlib-resources==5.2.2
    - iniconfig==1.1.1
    - markdown==3.3.4
    # - minkowskiengine==0.5.4 # installed manually
    - multidict==5.1.0
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - packaging==21.0
    - pathtools==0.1.2
    - pluggy==1.0.0
    - promise==2.3
    - protobuf==3.18.0
    - psutil==5.8.0
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pyparsing==2.4.7
    - pytest==6.2.5
    - python-dateutil==2.8.2
    - pytorch-lightning==1.4.7
    - pyyaml==5.4.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - sentry-sdk==1.3.1
    - shortuuid==1.0.1
    - six==1.16.0
    - smmap==4.0.0
    - subprocess32==3.5.4
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - termcolor==1.1.0
    - toml==0.10.2
    - torchmetrics==0.5.1
    - tqdm==4.62.2
    - urllib3==1.26.6
    - wandb==0.12.2
    - werkzeug==2.0.1
    - yarl==1.6.3
    - yaspin==2.1.0
    - zipp==3.5.0
